"""Unit tests for QueryEngine fallback mechanisms."""

from unittest.mock import MagicMock, patch
import pytest

from src.retrieval.query_engine import QueryEngine


@pytest.fixture
def mock_search_client():
    client = MagicMock()
    client.search.return_value = [
        {
            "content": "Enterprise customers may request a prorated refund within 30 days.",
            "metadata": {
                "file_name": "enterprise_sla.md",
                "page_number": 1,
                "section_heading": "Refund Policy",
            },
            "distance": 0.15,
        }
    ]
    return client


def test_query_engine_primary_model_success(mock_search_client):
    """Test that primary model is used when available."""
    qe = QueryEngine(
        search_client=mock_search_client,
        api_key="test-api-key",
        llm_model="gemma-4-26b-a4b-it",
        fallback_models=["gemini-3-flash-preview", "gemini-3.5-flash", "gemini-3.6-flash"],
    )

    mock_resp = MagicMock()
    mock_resp.text = "Enterprise refund window is 30 days."

    qe.client = MagicMock()
    qe.client.models.generate_content.return_value = mock_resp

    result = qe.query("What is the refund policy?")

    assert result.model == "gemma-4-26b-a4b-it"
    assert "30 days" in result.answer
    assert len(result.sources) == 1
    assert qe.client.models.generate_content.call_args[1]["model"] == "gemma-4-26b-a4b-it"


def test_query_engine_fallback_on_404_error(mock_search_client):
    """Test that QueryEngine falls back immediately if primary model gives 404."""
    qe = QueryEngine(
        search_client=mock_search_client,
        api_key="test-api-key",
        llm_model="gemma-4-26b-a4b-it",
        fallback_models=["gemini-3-flash-preview", "gemini-3.5-flash", "gemini-3.6-flash"],
    )

    def side_effect(model, **kwargs):
        if model == "gemma-4-26b-a4b-it":
            raise Exception("404 NOT_FOUND. Model not available.")
        mock_resp = MagicMock()
        mock_resp.text = f"Answer generated by {model}"
        return mock_resp

    qe.client = MagicMock()
    qe.client.models.generate_content.side_effect = side_effect

    result = qe.query("What is the refund policy?")

    assert result.model == "gemini-3-flash-preview"
    assert "gemini-3-flash-preview" in result.answer


def test_query_engine_fallback_on_429_quota_error(mock_search_client):
    """Test that QueryEngine falls back through candidate models on 429 quota exhaustion."""
    qe = QueryEngine(
        search_client=mock_search_client,
        api_key="test-api-key",
        llm_model="gemma-4-26b-a4b-it",
        fallback_models=["gemini-3-flash-preview", "gemini-3.5-flash", "gemini-3.6-flash"],
    )

    def side_effect(model, **kwargs):
        if model in ["gemma-4-26b-a4b-it", "gemini-3-flash-preview"]:
            raise Exception("429 RESOURCE_EXHAUSTED. Quota exceeded.")
        mock_resp = MagicMock()
        mock_resp.text = f"Answer generated by {model}"
        return mock_resp

    qe.client = MagicMock()
    qe.client.models.generate_content.side_effect = side_effect

    result = qe.query("What is the refund policy?")

    assert result.model == "gemini-3.5-flash"
    assert "gemini-3.5-flash" in result.answer


def test_query_engine_max_three_fallbacks(mock_search_client):
    """Test that at most 3 fallback models are attempted beyond the primary model."""
    extra_fallbacks = ["fb1", "fb2", "fb3", "fb4", "fb5"]
    qe = QueryEngine(
        search_client=mock_search_client,
        api_key="test-api-key",
        llm_model="gemma-4-26b-a4b-it",
        fallback_models=extra_fallbacks,
    )

    attempted_models = []

    def side_effect(model, **kwargs):
        attempted_models.append(model)
        raise Exception("404 NOT_FOUND")

    qe.client = MagicMock()
    qe.client.models.generate_content.side_effect = side_effect

    result = qe.query("What is the refund policy?")

    # Should attempt primary + exactly 3 fallbacks (fb1, fb2, fb3)
    assert attempted_models == ["gemma-4-26b-a4b-it", "fb1", "fb2", "fb3"]
    assert "Error generating answer" in result.answer
