"""Unit tests for QueryEngine fallback mechanisms."""

from unittest.mock import MagicMock
import pytest

from src.retrieval.query_engine import QueryEngine


@pytest.fixture
def mock_search_client():
    client = MagicMock()
    client.search.return_value = [
        {
            "content": "Enterprise customers may request a prorated refund within 30 days.",
            "metadata": {
                "file_name": "enterprise_sla.md",
                "page_number": 1,
                "section_heading": "Refund Policy",
            },
            "distance": 0.15,
        }
    ]
    return client


@pytest.fixture
def mock_llm():
    llm = MagicMock()
    llm.has_api_key = True
    return llm


def test_query_engine_primary_model_success(mock_search_client, mock_llm):
    """Test that primary model is used when available."""
    qe = QueryEngine(
        search_client=mock_search_client,
        llm_client=mock_llm,
        llm_model="gpt-4o-mini",
        fallback_models=["fb1", "fb2", "fb3"],
    )

    mock_llm.generate.return_value = "Enterprise refund window is 30 days."

    result = qe.query("What is the refund policy?")

    assert result.model == "gpt-4o-mini"
    assert "30 days" in result.answer
    assert len(result.sources) == 1
    assert mock_llm.generate.call_args[1]["model"] == "gpt-4o-mini"


def test_query_engine_fallback_on_404_error(mock_search_client, mock_llm):
    """Test that QueryEngine falls back immediately if primary model gives 404."""
    qe = QueryEngine(
        search_client=mock_search_client,
        llm_client=mock_llm,
        llm_model="gpt-4o-mini",
        fallback_models=["fb1", "fb2", "fb3"],
    )

    def side_effect(model, **kwargs):
        if model == "gpt-4o-mini":
            raise Exception("Error code: 404 - model not found.")
        return f"Answer generated by {model}"

    mock_llm.generate.side_effect = side_effect

    result = qe.query("What is the refund policy?")

    assert result.model == "fb1"
    assert "fb1" in result.answer


def test_query_engine_fallback_on_429_quota_error(mock_search_client, mock_llm):
    """Test that QueryEngine falls back through candidate models on 429 quota exhaustion."""
    qe = QueryEngine(
        search_client=mock_search_client,
        llm_client=mock_llm,
        llm_model="gpt-4o-mini",
        fallback_models=["fb1", "fb2", "fb3"],
    )

    def side_effect(model, **kwargs):
        if model in ["gpt-4o-mini", "fb1"]:
            raise Exception("Error code: 429 - Rate limit reached.")
        return f"Answer generated by {model}"

    mock_llm.generate.side_effect = side_effect

    result = qe.query("What is the refund policy?")

    assert result.model == "fb2"
    assert "fb2" in result.answer


def test_query_engine_max_three_fallbacks(mock_search_client, mock_llm):
    """Test that at most 3 fallback models are attempted beyond the primary model."""
    qe = QueryEngine(
        search_client=mock_search_client,
        llm_client=mock_llm,
        llm_model="gpt-4o-mini",
        fallback_models=["fb1", "fb2", "fb3", "fb4", "fb5"],
    )

    attempted_models = []

    def side_effect(model, **kwargs):
        attempted_models.append(model)
        raise Exception("404 NOT_FOUND")

    mock_llm.generate.side_effect = side_effect

    result = qe.query("What is the refund policy?")

    # Should attempt primary + exactly 3 fallbacks (fb1, fb2, fb3)
    assert attempted_models == ["gpt-4o-mini", "fb1", "fb2", "fb3"]
    assert "Error generating answer" in result.answer


def test_query_engine_missing_api_key(mock_search_client, mock_llm):
    """Test that a missing API key returns a helpful message without calling the LLM."""
    mock_llm.has_api_key = False
    mock_llm.key_env_name = "OPENAI_API_KEY"
    qe = QueryEngine(search_client=mock_search_client, llm_client=mock_llm)

    result = qe.query("What is the refund policy?")

    assert "OPENAI_API_KEY" in result.answer
    mock_llm.generate.assert_not_called()
